import React from 'react';
import { Card, CardHeader, CardBody } from '../ui/Card';
import { Brain } from 'lucide-react';
import { generateAISummary } from '../../data/mockData';

interface AISummaryProps {
  month: string;
}

const AISummary: React.FC<AISummaryProps> = ({ month }) => {
  const summary = generateAISummary(month);
  
  return (
    <Card className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-100">
      <CardHeader className="border-b border-blue-100">
        <div className="flex items-center">
          <Brain className="text-blue-600 mr-2" size={20} />
          <h3 className="text-lg font-medium text-gray-900">AI-Generated Insights</h3>
        </div>
      </CardHeader>
      <CardBody>
        <div className="prose prose-blue max-w-none">
          {summary.split('\n').filter(line => line.trim()).map((paragraph, index) => (
            <p key={index} className="text-gray-700">{paragraph.trim()}</p>
          ))}
        </div>
        <div className="mt-4 text-xs text-gray-500">
          These insights are generated by AI based on your spending patterns. Use them as suggestions to help improve your financial habits.
        </div>
      </CardBody>
    </Card>
  );
};

export default AISummary;